# -*- coding: utf-8 -*-
"""house

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yuO4YbMV4xWIH-KT6J4afEKk8-SYjxWv
"""

from sklearn.linear_model import LinearRegression
import numpy as np

# 模擬訓練資料（你可以根據實際情況調整）
# X: [[面積, 房間數, 房屋年齡]]
X_train = np.array([
    [30, 2, 10],
    [50, 3, 5],
    [70, 4, 2],
    [90, 5, 20],
    [110, 4, 15]
])
# y: 房價（單位：萬元）
y_train = np.array([300, 500, 700, 750, 800])

# 建立線性回歸模型
model = LinearRegression()
model.fit(X_train, y_train)

# 讓使用者輸入資料
print("歡迎使用房價預測系統！請輸入以下資訊：")

area = float(input("請輸入房屋面積（平方公尺）："))
rooms = int(input("請輸入房間數量："))
age = int(input("請輸入房屋年齡（年）："))

# 預測房價
user_input = np.array([[area, rooms, age]])
predicted_price = model.predict(user_input)

print(f"\n🏡 預測房價：約為 {predicted_price[0]:.2f} 萬元")